Repository team-winey/Winey-iOS, pull requests merged in 2023-09, with the labels that each got.

#163 [Fix, Feat] #158 - 2차QA
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/Image.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv2.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv2.imageset/img_mypage_lv2.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv2.imageset/mypg_기사.svg
  Winey/Winey/Source/Scenes/Alert/ViewController/AlertViewController.swift
  Winey/Winey/Source/Scenes/Guide/ViewControllers/GuideViewController.swift
  Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
  Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageGoalInfoCell.swift
  Winey/Winey/Source/Scenes/Recommend/ViewController/RecommendViewController.swift
Labels: Design 🎨, Fix ✍🏻, 영민 💪🏻

#167 [Feat] #166 갤러리 접근권한에 따른 분기처리 + .limited 케이스 전용 갤러리 뷰 제작 + 잔버그 수정
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_next.imageset/ic_next.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Sources/NavigationBar/WINavigationBar.swift
  Winey/Winey.xcodeproj/project.pbxproj
  Winey/Winey/Resource/Info.plist
  Winey/Winey/Source/Global/Extension/Foundation+/NotificationName+.swift
  Winey/Winey/Source/Global/Supports/SceneDelegate.swift
  Winey/Winey/Source/Global/Utils/PhotoManager.swift
  Winey/Winey/Source/Network/Service/Login/LoginService.swift
  Winey/Winey/Source/Scenes/Gallery/View/Cell/GalleryCell.swift
  Winey/Winey/Source/Scenes/Gallery/View/Cell/LimitedPickerCollectionViewCell.swift
  Winey/Winey/Source/Scenes/Gallery/ViewController/GalleryViewController.swift
  Winey/Winey/Source/Scenes/Gallery/ViewController/LimitedPhotoViewController.swift
  Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
Labels: Design 🎨, Fix ✍🏻, 응관 🧑🏻‍🍳

#165 [Fix] #164 - 사진 업로드 버튼 레이아웃 수정 및 닉네임 수정뷰 잔버그 수정
  Winey/Common/DesignSystem/Sources/DesignSystem/Sources/TextField/WITextFieldView.swift
  Winey/Winey/Source/Scenes/Gallery/ViewController/LimitedPhotoViewController.swift
  Winey/Winey/Source/Scenes/Login/View/LoginView.swift
  Winey/Winey/Source/Scenes/Login/ViewController/LoginViewController.swift
  Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
  Winey/Winey/Source/Scenes/Nickname/ViewController/NicknameViewController.swift
  Winey/Winey/Source/Scenes/Upload/View/PhotoUploadView.swift
  Winey/Winey/Source/Scenes/Upload/View/UploadBaseView.swift
  Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
Labels: Design 🎨, 응관 🧑🏻‍🍳

#168 [Fix] #161 - 2차 QA
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_banner4.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv1.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv1.imageset/img_level_1.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv1.imageset/img_mypage_lv1.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv2.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv2.imageset/img_level_2.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv2.imageset/img_mypage_lv2.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv3.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv3.imageset/img_level_3.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv3.imageset/mypg_귀족.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv4.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv4.imageset/img_level_4.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/img_mypage_lv4.imageset/mypg_황제.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/sample1.imageset/Contents.json
  Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
  Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
  Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageGoalInfoCell.swift
  Winey/Winey/Source/Scenes/TabBar/TabBarController.swift
Labels: bug, Fix ✍🏻, 인영 🙆🏻‍♀️

#170 [Fix] #169 - 피드백 반영
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/btn/btn_more.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/btn/btn_more.imageset/btn_more.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/btn/btn_more.imageset/btn_more.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_more.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_more.imageset/ic_more.svg
  Winey/Winey/Source/Global/Utils/PhotoManager.swift
  Winey/Winey/Source/Scenes/Detail/Views/CommentCell.swift
  Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
  Winey/Winey/Source/Scenes/Onboarding/AnimationOnboardingViewController.swift
  Winey/Winey/Source/Scenes/Recommend/ViewController/RecommendViewController.swift
  Winey/Winey/Source/Scenes/TabBar/TabBarController.swift
  Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
Labels: bug, Fix ✍🏻, 인영 🙆🏻‍♀️

#172 [Fix] #171 - 디자인 피드백 반영
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv1.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv1.imageset/img_profile_level_one.svg
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv1.imageset/normalProfileImg.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv2.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv2.imageset/Variant2.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv2.imageset/ic_profile_lv2.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv3.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv3.imageset/Variant3.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv3.imageset/ic_profile_lv3.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv4.imageset/Contents.json
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv4.imageset/Variant4.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/icons/ic_profile_lv4.imageset/ic_profile_lv4.pdf
  Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/img/Image.imageset/Contents.json
  Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
  Winey/Winey/Source/Scenes/MyPage/Views/Cells/MenuCell.swift
  Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageGoalInfoCell.swift
  Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageProfileCell.swift
Labels: Design 🎨, 영민 💪🏻

#175 [Fix] #173 - 테스트플라이트 버전 7 배포 후 피드백 반영
  Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Button/MIButton.swift
  Winey/Winey/Source/Global/Utils/PhotoManager.swift
  Winey/Winey/Source/Scenes/Detail/DetailMapper.swift
  Winey/Winey/Source/Scenes/Feed/View/FeedCell.swift
  Winey/Winey/Source/Scenes/Gallery/ViewController/LimitedPhotoViewController.swift
  Winey/Winey/Source/Scenes/Nickname/ViewController/NicknameViewController.swift
  Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
Labels: Design 🎨, Fix ✍🏻, 응관 🧑🏻‍🍳

#178 [Fix] #177 - 릴리즈 이전 코드 기능 점검
  Winey/Winey/Source/Scenes/Alert/ViewController/AlertViewController.swift
Labels: Fix ✍🏻, 영민 💪🏻

#179 [Feat] #143 토큰 만료 로직에 인터셉터 적용
  Winey/Winey/Source/Global/Supports/SceneDelegate.swift
  Winey/Winey/Source/Network/Base/CustomMoyaProvider.swift
  Winey/Winey/Source/Network/Service/Comment/CommentService.swift
  Winey/Winey/Source/Network/Service/Feed/FeedService.swift
  Winey/Winey/Source/Network/Service/FeedLike/FeedLikeService.swift
  Winey/Winey/Source/Network/Service/Goal/GoalService.swift
  Winey/Winey/Source/Network/Service/Login/LoginService.swift
  Winey/Winey/Source/Network/Service/Login/SessionInterceptor.swift
  Winey/Winey/Source/Network/Service/Nickname/NicknameService.swift
  Winey/Winey/Source/Network/Service/Notification/NotificationService.swift
  Winey/Winey/Source/Network/Service/Recommend/RecommendService.swift
  Winey/Winey/Source/Network/Service/User/UserService.swift
Labels: Fix ✍🏻, 응관 🧑🏻‍🍳, API 📡

#181 [Fix] #180 - 디스패치큐 메인에 endRefreshing() 추가
  Winey/Winey/Source/Scenes/Alert/ViewController/AlertViewController.swift
Labels: Fix ✍🏻, 영민 💪🏻

#183 [Add] #182 - 구글폼 링크 연결
  Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
Labels: Fix ✍🏻

#185 [Fix] #184 - 테스트 메뉴 제거
  Winey/Winey.xcodeproj/project.pbxproj
  Winey/Winey/Source/Scenes/TabBar/TabBarController.swift
  Winey/Winey/Source/Scenes/Test/TestPopupViewController.swift
  Winey/Winey/Source/Scenes/Test/TestTypoViewController.swift
  Winey/Winey/Source/Scenes/Test/TestUserViewController.swift
  Winey/Winey/Source/Scenes/Test/TestViewController.swift
Labels: Fix ✍🏻, 인영 🙆🏻‍♀️

#187 [Fix] #186 - 경고문구추가
  Winey/Winey/Resource/Info.plist
  Winey/Winey/Source/Global/Extension/UIKit/UILabel+.swift
  Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
Labels: Fix ✍🏻, 인영 🙆🏻‍♀️
